subscription ($friends: [String]) {
    newPostByFriend (friends: $friends) {
        username
        likes
        dislikes
        caption
        link
        postId
        madeOn
        likedBy
        dislikedBy
    }
}